"""empty message

Revision ID: 70201067e29c
Revises: b3c524245725
Create Date: 2023-10-12 15:14:41.423187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70201067e29c'
down_revision = 'b3c524245725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('wlid', sa.String(length=64), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('wx', sa.String(length=64), nullable=True),
    sa.Column('qq', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('wlid')
    )
    op.create_table('post',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pics', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('item',
    sa.Column('iid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['post.pid'], ),
    sa.PrimaryKeyConstraint('iid')
    )
    op.create_table('reply',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('pics', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['post.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('item')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
