"""empty message

Revision ID: 76532f5b6d14
Revises: 1ce6b12d142b
Create Date: 2023-10-18 20:00:31.330535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76532f5b6d14'
down_revision = '1ce6b12d142b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signiture', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signiture')

    # ### end Alembic commands ###
