"""empty message

Revision ID: e2b4eada724a
Revises: b34b88304634
Create Date: 2023-10-06 22:02:02.221679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b4eada724a'
down_revision = 'b34b88304634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('pics', sa.TEXT(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_url', sa.TEXT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wild', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wx', sa.VARCHAR(length=64), nullable=True),
    sa.Column('qq', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wild')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('items', sa.TEXT(), nullable=True),
    sa.Column('pics', sa.TEXT(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['post.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
