"""empty message

Revision ID: e89c00678649
Revises: 1eb3a087e7af
Create Date: 2023-10-03 20:57:15.276319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89c00678649'
down_revision = '1eb3a087e7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wild', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wx', sa.VARCHAR(length=64), nullable=True),
    sa.Column('qq', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wild')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wild', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('wx', sa.VARCHAR(length=64), nullable=True),
    sa.Column('qq', sa.INTEGER(), nullable=True),
    sa.Column('w', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'uid'),
    sa.UniqueConstraint('wild')
    )
    # ### end Alembic commands ###
