"""empty message

Revision ID: ea78f276571f
Revises: 76532f5b6d14
Create Date: 2023-10-20 01:21:15.303830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea78f276571f'
down_revision = '76532f5b6d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.String(length=64), nullable=True))
        batch_op.drop_column('signiture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signiture', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
